version: "3"
services:
  web-service:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:80
    command: ["npx", "nodemon", "app.js", "-L"] #esto tambien se agrega despues de iniciar la aplicacion
  mysql:
    image: mysql:8.0.35
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 33020:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: marketplace
      MYSQL_USER: user_marketplace
      MYSQL_PASSWORD: 54321
volumes:
  mysql_data: